name: Test Debian

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  test-install-common-dev-utils:
    strategy:
      matrix:
        tag: [ "11", "11-slim", "10", "10-slim", "9", "9-slim" ]
      max-parallel: 2
      fail-fast: false
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Debian
        run: docker pull debian:"${{ matrix.tag }}"

      - name: Run & Exec Script
        run: docker run --name "test-subject" "debian:${{ matrix.tag }}" "/bin/bash"

